package br.com.fiap.farmacia.models.enums;

public enum CategoriasDeProdutos {
    MEDICAMENTO_SEM_PRESCRICAO,
    MEDICAMENTO_CONTROLADO,
    HIGIENE_PESSOAL,
    HIGIENE_BUCAL,
    CUIDADOS_DA_PELE,
    VITAMINAS_E_SUPLEMENTOS,
    PARA_BEBES_E_CRIANCAS,
    CUIDADOS_DO_CABELO,
    PARA_OLHOS_E_OUVIDOS,
    PARA_ALERGIAS,
    PRIMEIROS_SOCORROS,
    SAUDE_MASCULINA,
    SAUDE_FEMININA,
    CUIDADOS_DOS_PES,
    PARA_MUSCULOS_E_ARTICULACOES,
    SAUDE_DIGESTIVA,
    PARA_UNHAS,
    PARA_IDOSOS
}
